# Generated by Django 4.0 on 2026-06-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taco',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='taco_images/'),
        ),
    ]
